### PR TITLE
Add description how to install the tool

### PR DESCRIPTION
**Pull request by christian-bromann**
I just watched the talk from @BethGriggs and wanted to try this tool. I saw that it wasn't published on NPM and I didn't want to clone the repo to start using it so there we go. Hope that is ok that I did. I will add all maintainers to package as admins.

### CODE REVIEW

**Comment by BethGriggs** [comment]
Hi! Thanks @christian-bromann, that's totally okay, and thank you (It was slight oversight prior to the talk).  We may mirror to `@pkgjs/dependents` in future but having dependents name is cool (surprised it was not already taken!)

**Review by BethGriggs — APPROVED** [review]

**Review by andrewhughes101 — APPROVED** [review]

**Review by dominykas — APPROVED** [review]

**Comment by dominykas** [comment]
Worth adding a note on `npx`?

**Comment by christian-bromann** [comment]
> Worth adding a note on `npx`?

What would you suggest?

**Comment by dominykas** [comment]
Something like "Or you can run `npx dependents [...]` to run it without installing"? Possibly also update the examples to go via `npx`.

**Pull request merged**
